services:
  slambook:
    build: .
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
      - XDG_RUNTIME_DIR
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/workspaces/slambook2/
    devices:
      - /dev/dri
    # privileged: true